### ISSUE TITLE
ref.py - can't load empty tables to the hdul using fits.BinTableHDU, and need to get rid of nans in data for linalg analysis

### ISSUE THREAD

**Issue by PK0207** [deepspace-ucsb/sdi_pipeline#101]
**Describe the bug**
The error that shows up is:
`TypeError: Table data has incorrect type.`
When using `ref.py` in the following pipeline command:
`sdi read -d GTAnd_SCI_small/ align subtract extract -w CAT 1 ref write -d sdiPTF_output_final/`

**To Reproduce**
1. Go to '/home/pkotta/pipeline_editing'
2. Run the venv using the following command: `source ./bin/activate`
3. Run the pipeline command above from the home directory (/home/pkotta)

**Expected behavior**
I expect the code to be able to skip an empty array of data (i.e. when nothing is found in the reference database).
If it does find something, I expect it to load a corresponding fits file into the write directory.
That fits file should have the reference information in the `[REF]` header extension

**Desktop (please complete the following information):**
- Last pulled from sources: 7/11/21

**Additional context**
Working on GTAnd files from PTF, so I have to use code from the branch ref-testing_pk as it requires a byteswap, and x,y information in the CAT files outputted from extract

**Comment by varun-magesh** [comment]
What line does the TypeError appear in?

**Comment by PK0207** [comment]
> What line does the TypeError appear in?

Appears in the following line: `hdul.append(fits.BinTableHDU(data=output_table, header=header, name=extname))`
I think in master it's line 123

**Comment by PK0207** [comment]
I added a try except loop, making it run a pass in case it runs into a TypeError and it worked on a small set of 6 images, running now on all images. This is a bandaid fix for now.

**Comment by PK0207** [comment]
Ran it all on images, it seemed to work! This was without phot_bp_mean_mag though, which I need for normalization.

**Comment by PK0207** [comment]
**NOTES FROM MEETING 07/21 - getting rid of nans**
ref.py - line 114 onwards (for norm_sources branch) is possibly where the nans come from, need to change to 0s.

nans could also be coming from within the database, in which case it would be nice if we can replace those nans with 0s in ref.py

Use pdb.set_trace() to traverse the output table and other outputs in ref more easily (look up usage)

**Comment by PK0207** [comment]
Add an output warning for when a data output table comes up empty. Make sure to add the reason why this might happen.

**Comment by benfogiel** [comment]
added warning message for empty reference table
