### ISSUE TITLE
Implement PCA

### ISSUE THREAD

**Issue by nlynn** [deepspace-ucsb/sdi_pipeline#103]
Implement Brandt's PCA code to try to improve error analysis.

**Comment by nlynn** [comment]
- [x] Implement Brandt's code
- [ ] See if we can interpret signal/noise in the principle components 
- [ ] Determine PCA's place on the pipeline

**Comment by PK0207** [comment]
Brandt's code runs on some test images, dunno how to interpret the result quite yet.

**Comment by PK0207** [comment]
- [ ] Where does the variation come from? Look into the math to answer that question. What is the value on the graph?
- [ ] What does each dimension correspond to? In terms of physical source of the dimension.
- [ ] Variable detection is a possible use case

**Comment by PK0207** [comment]
Got the entire script working with LCO images (Don't run on more than 20 images, runs slow and no point for our testing purposes). Tested on section 18 newer images and not much variability to discuss. Moving on to see how to check for where each PC comes from, and:

- [ ] Test on simulated RR Lyrae images
- [ ] Test on Real PTF images

**Comment by PK0207** [comment]
No longer relevant
