### ISSUE TITLE
Move main SDI to /home/starmaker

### ISSUE THREAD

**Issue by agthomas-ucsb** [deepspace-ucsb/sdi_pipeline#112]
Change the default so importing SDI imports from Starmaker's installation. This allow Varun to work on his own version without impacting the rest of the project and Starmaker's installation can be scripted to pull the latest version from GitHub every 24 hours so we ensure it stays seamlessly up to date and centralized in an easy location.

**Comment by nlynn** [comment]
Same as issue #116
