### ISSUE TITLE
Observing Plans for Fall: Aug 2021-Jan 31st 2022

### ISSUE THREAD

**Issue by nlynn** [deepspace-ucsb/sdi_pipeline#117]
For all images:
-10 sec integration time
-100 image count per filter 
-Filters: SDSS u, g, i
-Images should be taken every 2 weeks (preferably). 
-Having 5 observations of each section would be nice by the end of the run
-Focus on sections with existing data on Starmaker first

### M31 Aug-Feb

Sections: (Ideal sections that we'd get a backlog of data of--prioritize those that we already have data in for lightcurve generation) 
RA: 00h 42m 44.3s
DEC: +41° 16′ 9″
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 14
- [ ] 15
- [ ] 16
- [ ] 17
- [ ] 18
- [ ] 21
- [x] #130
- [x] 23
- [x] 24
- [ ] 25
- [ ] 26
- [ ] 29
- [x] 30
- [x] 31
- [x] 32
- [x] 33
- [ ] 34
- [ ] 28
- [ ] 29
- [ ] 40
- [ ] 41
- [ ] 42
- [ ] 46
- [ ] 47
- [ ] 48

### LMC Aug-Mar RA/DEC: 05:23:35/-69:45:22
Sections: (Ideal sections that we'd get a backlog of data of--prioritize those that we already have data in for lightcurve generation) 
- [ ] 23
- [ ] 24 
- [ ] 25
- [ ] 21
- [ ] 34
- [ ] 35
- [ ] 28
- [ ] 29
- [ ] 30
- [ ] 31
- [ ] 32
- [ ] 33

### SMC Jun-Jan RA/DEC: 00:52:49/-72:49:43
Sections: (Ideal sections that we'd get a backlog of data of--prioritize those that we already have data in for lightcurve generation) 

- [ ] 3
- [ ] 5
- [ ] 7
- [ ] 8
- [ ] 12
- [ ] 13
- [ ] 14
- [ ] Make new mosaic ASAP
- [ ] Figure out sections to image 
- [ ] For now, take images of the sections we already have data for:

**Comment by agthomas-ucsb** [comment]
![m31 mosaic](https://user-images.githubusercontent.com/82772028/132967007-0d6c2d5e-d25d-4883-a59d-0ceed0039514.png)

**Comment by agthomas-ucsb** [comment]
Queued all sections checked and the first round of 7,8,9, 14

**Comment by agthomas-ucsb** [comment]
Verified 22-24, and 30-33 were successful. Proceeding with second and third rounds for 7, 8, 9, 14 and queueing new sections.

**Comment by agthomas-ucsb** [comment]
TimeAllocationError("An IPP Value of 1.05 requires more IPP time than you have available for 'NORMAL' Observation with the 0M4-SCICAM-SBIG . Please lower your IPP Value to <= 1.027 and submit again.")
while request v2 for 14, after 7, 8, 9 requested successfully.

**Comment by agthomas-ucsb** [comment]
Fixed error by reducing IPP time to 1.00 (normal). For some reason it defaults to 1.05? Queued remaining requests for 7, 8, 9, 14 and three rounds for 15, 16, 17, 18.

**Comment by agthomas-ucsb** [comment]
Ran out of hours before additional imaging could come back. We're considering requesting more but might be good for this year.

**Comment by agthomas-ucsb** [comment]
To date we have data from: 11, 13, 23, 24, 31, 32, 33, 38, 40, 41, 42, 47
It seems 30 was never downloaded from LCO
