### ISSUE TITLE
Make vis.py a part of the pipeline tools.

### ISSUE THREAD

**Issue by PK0207** [deepspace-ucsb/sdi_pipeline#125]
**Is your feature request related to a problem? Please describe.**
Knowing what sources the pipeline finds, and with what efficacy is something that I often have to do,, and it's nice to visualize it on the image itself. So, the code that Kelvin made a while ago comes in handy but since it was made for only a couple people to use it isn't the most intuitive to use.

**Describe the solution you'd like**
Using vis.py existing code:
1. Open the image in ds9 using the image command
2. Have an option in circle() to convert from RA/DEC to xy
3. Change the code such that it takes in the hdul, rather than a list of coordinates (basically all should be contained in the code)

**Describe alternatives you've considered**
Alternatives not considered, this is a novel feature thanks to Kelvin!

**Additional context**
This is all in the context of **existing vis.py code**. Please see that code to understand the issue better.

**Comment by varun-magesh** [comment]
Closed, use case covered by `sdi display`.
