### ISSUE TITLE
Creating a uniform way of dealing with HDU’s through the pipeline 

### ISSUE THREAD

**Issue by JasperWebb** [deepspace-ucsb/sdi_pipeline#129]
**Is your feature request related to a problem? Please describe.**
Currently each of the main scripts has a different method of saving/appending whatever changes are made within to the HDUL. Either completely overwriting the HDUL with a single HDU or appending to the beginning/end of HDUL. If the goal is to be as non-destructive , maintaining as much science data as possible, we should be appending any changes to a new **named** HDU. 
I’ll update this with a map of the HDUL through the pipeline shortly. 

**Describe the solution you'd like**
A definitive plan/structure on how we should handle HDU’s and HDUL’s in the pipeline.

**Comment by JasperWebb** [comment]
HDUL's through the pipeline [Currently in norm_sources_merge] 
idx---EXTNAME---HDUType---description)
**raw input (This is possibly just LCO's structure. I'm not sure about other data sources):**
- 0---Primary---PrimaryHDU---(default HDU, empty header and data)
- 1---SCI---CompImageHDU---(image data  and header cards)
- 2---CAT---BinTableHDU---(sources?)
- 3---BPM---CompImageHDU---(bad pixel mask)

**read align write:** 
- 0---SCI---PrimaryHDU---(aligned data and header cards from raw SCI)

**read align subtract (numpy for speed HDUL should be unaffected) write:**
- 0---Primary---PrimaryHDU---(contains residual image? empty cards)
- 1---HEADER_DATA---CompImageHDU---(contains all cards no data)
- 2---SCI---Image HDU---(contains all cards and original data?)

**read align subtract (numpy for speed HDUL should be unaffected) extract write:** 
- 0---Primary---PrimaryHDU---(contains residual image? empty cards)
- 1---HEADER_DATA---CompImageHDU---(contains all cards (minus 2??) no data)
- 2---SCI---Image HDU---(contains all cards and aligned data?)
- 3---XRT---BinTableHDU---(71 cards extracted sources?)

**Comment by JasperWebb** [comment]
Through the pipeline the format of the HDUL changes quite significantly. 
1. Align -- In the output of `align `the original HDUL is overwritten with a single PrimaryHDU called 'SCI' This contains all of the header cards from the original image aswell as the aligned image data. I'm not sure if its necessary to keep CAT or BPM from the raw HDUL. I believe that by aligning the image the sources in CAT will be disconnected from the x/y position in frame if i understand how align works. 

2. Subtract-- Subtract needs some tidying up in its current form. Currently the residual image and the header cards are written into seperate HDU's. (Primary and HEADER_DATA repectively) In subtract as a minimum we should have the aligned image, and the subtracted image in the HDUL. Currently the sub image is stored in Primary. I think this should change to a separate ImageHDU/CompImageHDU called sub. Ideally it would be indexed before SCI as DS9 by default opens the lowest index HDU with image data. [Purely QoL. SDI_display works for this aswell.] 

3. Extract-- I think extract works correctly in this instance. Simply appending the XRT BinTableHDU to the end of the HDUL

**Comment by JasperWebb** [comment]
Approach -->
Align. add HDU called ALGN containing aligned data. Can be inserted in index 1 of hdul. 
HDUL after Align.py would look like: 

    0---Primary---PrimaryHDU---(default HDU, empty header and data)
    1---Aligned---ImageHDU---(Aligned image data and header cards)
    2---SCI---CompImageHDU---(image data and header cards)
    3---CAT---BinTableHDU---(sources?)
    4---BPM---CompImageHDU---(bad pixel mask)
Just have to be careful about downstream scripts looking for "SCI" instead of Aligned
![image](https://user-images.githubusercontent.com/10064835/137227762-4be77d2f-74b2-4098-8a79-6e87a62e6fe8.png)

**Comment by JasperWebb** [comment]
Subtract.  Subtracted data is inserted into HDUL in 1st index containing both data and header. 
I had to edit `combine.py` to make it work. (changed the default parameters to point at "ALGN" header instead of "SCI")

![image](https://user-images.githubusercontent.com/10064835/137232944-5bf38fee-6323-4ab7-bd13-f2a1d30fd2e9.png)

**Comment by JasperWebb** [comment]
This is the HDUL after read align subtract extract write. The file size is quite large (52MB) 
![image](https://user-images.githubusercontent.com/10064835/137264035-59190a7d-bef3-42df-a6cb-a96eafbd6d28.png)

**Comment by JasperWebb** [comment]
We could probably replace SCI with ALGN and drop the BPM and CAT table in index 4 as they're misaligned w.r.t ALGN & SUB

I'm not 100% sure of the difference between CompImageHDU and ImageHDU other than one is compressed.

**Comment by JasperWebb** [comment]
Changing all the ImageHDU's to CompImageHDU drops the processed file size to 16.5MB.  
![image](https://user-images.githubusercontent.com/10064835/137408156-9ba138f5-0f38-4bc7-a29b-f341faafc4cf.png)

**Comment by PK0207** [comment]
> Changing all the ImageHDU's to CompImageHDU drops the processed file size to 16.5MB. ![image](https://user-images.githubusercontent.com/10064835/137408156-9ba138f5-0f38-4bc7-a29b-f341faafc4cf.png)

Does this affect anything about the images functionally? Like how they are opened, read, edited, and visualized?
(Sorry not totally familiar with the difference bw CompImage and Image)

**Comment by JasperWebb** [comment]
I found this in the docs: 
https://docs.astropy.org/en/stable/io/fits/#working-with-compressed-files

**Comment by JasperWebb** [comment]
Changes merged to Master
