### ISSUE TITLE
Choosing Reference stars

### ISSUE THREAD

**Issue by PK0207** [deepspace-ucsb/sdi_pipeline#134]
**Describe the science task**
We are trying to investigate the nest method to choose reference stars. Choosing the right reference stars will give us a better result for determining the magnitude of the stars in our images. Then, we can use standard mag-to-flux equations to determine the magnitude of the star.

**Proposed Direction**
First, we should explore how to do this manually, so that we can determine how to do this programmatically. My idea is to first choose one of our stars, and look it up in the SIMBAD database using coordinate query, and then find reference stars that are:
* In the same image
* Of the same type
Then, using the information on SIMBAD for the reference stars, we can try to find the magnitude of our star and see if it matches that on SIMBAD.
Then, we can convert the magnitude of the reference stars to SDSS g' using the code I have prepared, and find the magnitude of our star again, and see if it is reasonably close to the accepted value.
Finally, we can find reference stars that are not of the same type as our chosen star, and see if the above methods result in serious performance depreciation.
**Desired Results**
We want to have a good sense of the information required to get the accurate magnitude of a given star, using reference sources. Then we want to be able to expand that to a general program that does this for all stars in one image.

**Resources**
* Refer to PDF in slack - for photometric systems
* To measure the sky Frederick and Chromey - for flux to mag
* Any other resources you find, please share.

**Additional context**
This is a step in making sure norm_sources is functional and correct.

**Comment by PK0207** [comment]
Chose reference stars that were:
- Closest to the target star
- Non-variable
- brighter than the target star
Found magnitudes that seemed in the right range (16.7-17.5 reported, ours are 16.69 - 17.9),
linear fit from test run seemed to be accurate: <br>
![image](https://user-images.githubusercontent.com/30590837/151907381-55df84ec-9a97-4102-b1c8-8f7cad875b99.png)


TODO:
- Make sure ref stars are not variable

Residuals are very large:
- collate might end up finding just one comp star, or too few comp stars
- Instead of taking the mean when doing photometry, iterate through each point
- Residuals might not be the best error indicator

**Comment by EdgarMao** [comment]
A quick trial light curve

![lightcurve_trial1](https://user-images.githubusercontent.com/31234107/151907931-aa9ce2ae-70d3-4d6e-b7f1-0f7cd88626c1.png)

**Comment by PK0207** [comment]
PTF confirmed that the images are bias subtracted and flat-fielded

**Comment by PK0207** [comment]
Method used for choosing reference stars:

- Reference stars are close to the target star. This limits the effects of differences in seeing across the image. A radius of 0.03 degrees finds us 24 reference stars when specifically using GTAnd images from PTF.
- Reference stars are non-variable. If they were variable then the photometry would be greatly affected and incorrect.
- Reference stars are brighter than the target star. This has a few effects. One, since gaia can find very dim stars, this removes any stars that would not be found in our catalog, and for which we would have no data. Two, this ensures that the clustering algorithm can find the stars more effectively, because the performance of extract is also better with brighter stars. Finally, if the reference stars are brighter than the target, we can be sure that photometry is being done well. The performance of the linear fit is improved with brighter stars.
- Reference stars do not have any missing values: Collating the stars sometimes results in missing values (represented by 0s), which indicates that collate could not find that star in that image. This means that we do not use the same reference stars across all images, making the photometry unreliable. This is where we lose most of our stars, (24 -> 6 for PTF)
- Removing images (and reference star instances) whenever the target star could not be found.

This is the current procedure we have in place for selecting reference stars. It is not all done in one function, but rather scattered across the program. We can see if we can programmatically improve the efficacy of this search. Closing because process is settled.
