### ISSUE TITLE
TypeError in Align

### ISSUE THREAD

**Issue by coleslenkovich** [deepspace-ucsb/sdi_pipeline#159]
**Align Generates a TypeError when Running Master Pipeline**
When running fits images through our master pipeline, some of us are experiencing a TypeError with the data. The issue seems to occur in astroalign, when called in the Align function. The function is find_transform, error occurs on line 221. (Screenshot below)

**To Reproduce**
Run following line:
sdi read -d /path/to/fits/ align subtract extract write -d /path/to/save/location

**Screenshots**
![Screen Shot 2022-04-06 at 1 41 16 PM](https://user-images.githubusercontent.com/71855559/163468917-78f61e93-04f4-476a-a341-c2e9df58f7c5.png)
<img width="722" alt="Screen Shot 2022-04-14 at 1 26 48 PM" src="https://user-images.githubusercontent.com/71855559/163470048-a0b0bfb1-657c-4b79-a39c-1c8bd48b4daf.png">

**Comment by JasperWebb** [comment]
I've tried running the nebula version of the pipeline with the Command line arguments: 
sdi read -d ~/Desktop/Fits/raw/ align subtract -m numpy extract write -d ~/Desktop/Fits/processed

I'm getting this same error

**Comment by JasperWebb** [comment]
I created a branch of the Master branch into my VENV and the pipeline ran as expected. 
Running the pipeline from a new terminal window causes the crash shown by Cole above.

**Comment by JasperWebb** [comment]
@agthomas-ucsb Can you look into this please.
