### ISSUE TITLE
What is the reference image in subtract

### ISSUE THREAD

**Issue by kyledereklam** [deepspace-ucsb/sdi_pipeline#170]
**Describe the bug**
Not a bug, but I am not sure what the difference between the target image and the reference image is in the code.

So the template, which is what is used to subtract against the aligned science image is denoted by:
`template = combine(hduls, name)["PRIMARY"].data`
**What is combined?** I see it as like somehow combining(?) or doing something the images denoted with the default name "ALGN" 

The problem it seems that the reference image and the target image are the same thing, as seen by here in the code for ois:
`diff = ois.optimal_system(**image=hdu[name].data**, refimage=template, method='Bramich')[0]`
Or here in NumPy
`diff = template - hdu[name].data`
What's the difference between hdu[name] and the template that was created from name?

**Comment by agthomas-ucsb** [comment]
This issue was solved in meetings. The reference image is the median value of each pixel in the image stack.
