### ISSUE TITLE
Use js9 to make clicky-click UI to view stuff

### ISSUE THREAD

**Issue by nlynn** [deepspace-ucsb/sdi_pipeline#3]
**M** [JS9](https://js9.si.edu/) in-browser fits viewer. Useful for viewing stuff when ssh-ed into pipeline

**Comment by varun-iyer** [comment]
Much harder than I thought. Good luck.

**Comment by varun-magesh** [comment]
JS9 ended more difficult than I thought. A more doable task might be to get `pyds9` to open over X port forwarding. Take a look at [vis.image](https://github.com/ucsbdeepspace/sdi_pipeline/blob/133e72d786704c1dadadd1c9682696a7d7a3f511/vis.py#L15) for where this is done.
