### ISSUE TITLE
Incorporate light curve analysis techniques from Lomb Scargle Paper

### ISSUE THREAD

**Issue by PK0207** [deepspace-ucsb/sdi_pipeline#32]
Implement methods outlined in https://iopscience.iop.org/article/10.3847/1538-4365/aab766/pdf 

- [ ] 2. Compute the window transform using the Lomb–Scargle periodogram, by substituting g_n1 for each t_n and making sure not to precenter the data or use a floating-mean model. Examine this window function for dominant features, such as daily or annual aliases or Nyquist-like limits
- [ ] 3. Use thefloating-mean model
- [ ] 4. Plot the periodogram and identify any patterns that maybe caused by features you observed in the window function power. Plot reference lines showing several FAP levels to understand whether your periodogram peaks are significant enough to be labeled detections: use the Baluev  method  or  the  bootstrap  method  if  it  is computationally feasible
- [ ] 5. If the window function shows strong aliasing, locate the expected multiple maxima and plot the phased light curve at each.
- [ ] 7. Inject known signals into the pipeline to measure your detection efficiency as a function of object type, brightness, and other relevant characteristics

**Comment by nlynn** [comment]
Natalie:
- [ ] Determine false positive rates 
- [ ] F1 statistic--rigorous statistical treatment
