### ISSUE TITLE
quantitative results for dbscan

### ISSUE THREAD

**Issue by nlynn** [deepspace-ucsb/sdi_pipeline#40]

**Comment by varun-magesh** [comment]
a very brief, quantitiative discussion that's less like "here is how this really cool algorithm works" (which i'm really fond of but is for a future paper) and more like "these data show that this alrogithm works"

**Comment by kyyip** [comment]
https://docs.google.com/document/d/14LekxnMYrxI07eclXDlTmzlE3rX6hrcGOUBeIhNdwGc/edit?usp=sharing
