### ISSUE TITLE
Config Files

### ISSUE THREAD

**Issue by nlynn** [deepspace-ucsb/sdi_pipeline#5]
**M** Configuration files: figure out how hotpants/OIS/sep are configured and create a YAML config file

**Comment by varun-magesh** [comment]
Configurable values like threshold amounts, file directories, etc. should go in a `yaml` file rather than directly in python. This is currently in [`config.__init__`](https://github.com/ucsbdeepspace/sdi_pipeline/blob/133e72d786704c1dadadd1c9682696a7d7a3f511/config/__init__.py#L19).
