### ISSUE TITLE
Relate dwell time + SNR calculations in introduction to results throughout the paper

### ISSUE THREAD

**Issue by varun-magesh** [deepspace-ucsb/sdi_pipeline#50]
Specific areas that could use this are the observation section; justifying our observations w.r.t. expected flux/SNR from civ. class and dwell time.
Other areas are differencing results + light curve results & simulation; comparing the results we achieved with the kinds of signals we'd get from DE communications.

**Comment by nlynn** [comment]
Also re justify why we are doing optical SETI

**Comment by varun-magesh** [comment]
Some answers to that: unexplored, it's the telescopes we have, physical constraints on directed energy
