### ISSUE TITLE
`subtract` should support AdaptiveBramich as an option

### ISSUE THREAD

**Issue by varun-magesh** [deepspace-ucsb/sdi_pipeline#70]
- [x] figure out how to include the custom `ois` in `sdi` :star: **hard** :star: 
- [x] create a new 'method' argument for `subtract`
- [ ] Implement the AdaptiveBramich `optimal_image` in `subtract`
- [ ] Have good error handling if there is no GPU
- [x] add `method` option in `subtract_cmd`

**Comment by varun-magesh** [comment]
@YaelBB:

Here are the steps just to get things up and running with `ois`, before we hit the tasks to incorporate it correctly above:

- [x] Make a `venv`
- [x] Install the ois version hosted at `https://github.com/varun-iyer/ois`
- [x] Install sdi from `https://github.com/ucsbdeepspace/sdi_pipeline`
- [x] Modify `subtract` to use AdaptiveBramich

**Comment by nlynn** [comment]
Adaptive bramich has been implemented--see the wiki for how to use
