### ISSUE TITLE
`ref` should include x-y information

### ISSUE THREAD

**Issue by varun-magesh** [deepspace-ucsb/sdi_pipeline#74]
This issue is closely related to #36; as a matter of convenience, we should copy over the x-y coordinates from the `CAT` table so we can locate reference stars on an image.

**Comment by PK0207** [comment]
I see that it's in my copy, and I think what I did was write a new CAT file after the extract process, and used those x and y coordinates.

**Comment by PK0207** [comment]
- [x] Find out what coord frame gaia is in

**Comment by PK0207** [comment]
Gaia coords are in ICRS frame

**Comment by PK0207** [comment]
Add a check in ref.py to see what frame images are in, or add an input

**Comment by PK0207** [comment]
This is not possible, because we do not have WCS information for reference stars. WCS information tells us the location of the telescope and other alignment and distortion parameters necessary for conversion of radec to image xy.
