### ISSUE TITLE
Generate docs correctly with Sphinx

### ISSUE THREAD

**Issue by varun-magesh** [deepspace-ucsb/sdi_pipeline#75]
Currently, our Sphinx pages at ucsbdeepspace.github.io/sdi_pipeline is... not really working. However, our code is in fact decently documented, and we do have an open issue improving it (#25).

It would be really nice if we could have the documentation generated nicely.

Some fixes will probably be necessary for the new project structure.
Ask Robby for the Sphinx generation stuff.

**Comment by EdgarMao** [comment]
This is an initial draft of an up-to-date documentation page: #100

**Comment by EdgarMao** [comment]
A documentation page has been successfully generated and is currently online: https://ucsbdeepspace.github.io/sdi_pipeline

Instructions about updating the documentation page after making changes to the pipeline has been given in the following wiki page: https://github.com/ucsbdeepspace/sdi_pipeline/wiki/Updating-Documentation-with-Sphinx . Further information about adding contents onto the documentation page can also be found in the wiki page.
