### ISSUE TITLE
Implement SNR As a Library Feature & Command

### ISSUE THREAD

**Issue by varun-magesh** [deepspace-ucsb/sdi_pipeline#76]
`_scripts/snr`is a helper function that accepts a list of hduls and returns the one that has the highest signal to noise ratio.
While this is nice, it would be helpful to be able to use it in a more flexible way, including on the command line. Ultimately, we would like to be able to use `snr` as an sdi command which adds an `snr` value to the FITS header of the appropriate data table.

- [x] Move `_scripts/snr => sdi/snr`
- [x] Rewrite `snr` to return a modified collection of hduls instead of the best hdul
- [x] Rewrite `align` to use the new API description of snr
- [x] Add snr to `sdi/__init__`
- [x] Add an `snr_cmd` which exposes `snr` to the public CLI

**Comment by JasperWebb** [comment]
A lot of what the new snr script does is also done in extract.
