### ISSUE TITLE
`subtract` should add RA/DEC information to the header

### ISSUE THREAD

**Issue by varun-magesh** [deepspace-ucsb/sdi_pipeline#77]
Currently it's very easy for users to lose track of the associated data and have no clue what section or coordinates are associated with their residual data.

**Comment by JasperWebb** [comment]
@varun-iyer This issue stems from the FIXME/output issue Edgar fixed in #102 . Instead of rebuilding each hdul and dropping all but the primary HDU. Subtract now appends the new subtracted data to the original list. The fix was applied to ` norm-sources`.
