### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by varun-magesh** [deepspace-ucsb/sdi_pipeline#83]
Currently, when we make changes to the pipeline, we (and reviewers) have to manually download and verify that it works. Often there are gaps that are only discovered later. We should have automated tests that we can run locally and through GitHub that verify that the pipeline works as intended.

This unit testing is primarily aimed at code functionality, not scientific efficacy, which should be done through purpose-designed testing.

This should probably be done through the `unittest` module.

**Comment by benfogiel** [comment]
Basic implementation for each test is done. Talked to Varun earlier today to further improve tests by comparing test outputs to pre-generated outputs that are known to be accurate. Currently working on these improvements.

**Comment by benfogiel** [comment]
Just committed current progress (documented in last comment) to Unit-Testing branch

**Comment by benfogiel** [comment]
Finished the combine, read, and write test functions, ready for review. Still working on the other test functions. Haven't submitted any merge requests because don't think it is possible to merge a selective portion of a branch (might be wrong)

**Comment by benfogiel** [comment]
pull request submitted

**Comment by JasperWebb** [comment]
The files for unit testing will need to be regenerated for unit testing as the order of HDUL's has changed quite significantly with the most recent update to master. 
@benfogiel
