### ISSUE TITLE
Implement `collate`

### ISSUE THREAD

**Issue by varun-magesh** [deepspace-ucsb/sdi_pipeline#86]
This command line and API function should do what `cluster` generally does.
Given a collection of HDUList and a TableHDU specified by an `EXTNAME`, return a collection of HDUList with the `EXTNAME` table organized such that the Nth index of each table refers to the same sky object (as best as we can tell).

**Comment by varun-magesh** [comment]
@kyyip pr #94 addresses this.

**Comment by kyyip** [comment]
It's done!
