### ISSUE TITLE
Simulated RR Lyra lightcurve

### ISSUE THREAD

**Issue by PK0207** [deepspace-ucsb/sdi_pipeline#87]
**Describe the science task**
See if the method used currently for the process of referencing, normalizing, and producing a lightcurve works for a simulated set of images.

**Proposed Direction**

1. Build a set of 100+ simulated images of an RR Lyra based on a generic magnitudes list
2. Run the pipeline on the images, run the database code.
3. Run phase diagram on it.

**Desired Results**
The generated lightcurve and the original lightcurve should have the same period and magnitudes (we should be able to produce the same exact curve with a controlled, calculable error)

**Resources**
Data to be used might be from PTF (The idealized magnitudes), the rest should be our scripts.

**Additional context**

- This is to pinpoint any issues the current method has, and why we cannot produce the exact lightcurve from the PTF images.
- This pipeline will be run with 1 reference star, and if that works, multiple reference stars.

**Comment by PK0207** [comment]
relative brightness, normalization, LCO type data

**Comment by PK0207** [comment]
HDULs still need to have the SCI extension, not sure how to specify a source and cat extension

Command:  sdi read -d image_fits/ align subtract extract write -d sditest_output
KeyError: "Extension 'SCI' not found."

**Comment by PK0207** [comment]
Residuals stars are barely visible, and the XRT file that contains the extracted data comes up empty

**Comment by PK0207** [comment]
**ERROR** Big-endian buffer not supported on a little-endian compiler
**FIXED** 

![image](https://user-images.githubusercontent.com/30590837/120125990-a34a0580-c16f-11eb-9e6a-a9ece822fcdd.png)
BITPIX changed in header info

**Comment by PK0207** [comment]
**ERROR** ['SCI'] not found
**FIXED** Added ['SCI'] to HDUL tags (Cole and Kelvin)

**Comment by coleslenkovich** [comment]
RR Lyrae only shows up on certain images in the residual set. Residual images look empty, but a few of the images contain the RR Lyrae at (1600,1050).
 - Lowering the background noise added in false transients into residual images and didn't noticeably affect our ability to the RR Lyrae

**Comment by PK0207** [comment]
Remade the images with lc_GTAnd.csv instead of GTAnd_PTF_lc.csv, images are called image_fits3

**Comment by PK0207** [comment]
flux not loaded into resulting CAT table after everything is run through the pipeline, will run again to see if this is a recurring issue.
EDIT: Happened again on the second run. This does not happen to normal files run through, and has not happened before so I don't know what's going on.

**Comment by PK0207** [comment]
Files for testing are in /home/bfogiel/issue_87. This includes 10 simulated images, and the original csv file for the variable star
**Reading the .csv file**

row = np.genfromtxt('lc_GTAnd.csv',delimiter='\t')
time = []
magauto = []
magerr = []
for row in data:
    time.append(row[0])
    magauto.append(row[1])
    magerr.append(row[2])

**The resulting data**
The resulting images should have the the PRIMARY hdu and the BINTable hdu (Should be named CAT). 
The CAT table is the result from extract.py . It is called the catalog file, and it contains lists of data, where each list item corresponds to one object from the original image.
**The issue**
Currently, the table is either missing data entirely, or missing flux specifically. The command run is as above. Issue is most likely with extract, or the way the images are created. (i.e., extract doesn't have enough information in the headers to find flux)

**A new branch should be made for testing**

**Comment by benfogiel** [comment]
Finally got a light curve (figure below). It is not similar to the control image. This could be due to some tweaks that I made when calculating flux error, although, changing the flux error values does not seem to change the plot much. What was a bit odd was that there are not a lot of flux values, the source of this could be the clustering function (not sure though). Will need to review this with @PK0207 at our meeting today.
![freq_pow](https://user-images.githubusercontent.com/52505296/137784378-b4238f8c-1e36-45ff-8165-68318450d99e.PNG)

**Comment by benfogiel** [comment]
For reference, here is the control ima
![control](https://user-images.githubusercontent.com/52505296/137784632-56f4cd6f-37c5-410e-a362-f682ed4f290d.PNG)
ge

**Comment by benfogiel** [comment]
Getting the fluxes directly from the image results to the following gra
![pow_freq](https://user-images.githubusercontent.com/52505296/137983949-2e16a5ef-b998-4cc0-9f8b-97b4c72e747f.PNG)
ph

**Comment by PK0207** [comment]
Not using simulated images anymore
